version: '3.9'
services:
  server:
    image: "monitor-server"
    volumes:
      - ./logs:/logs
    environment:
      - NODE_INFO_LOG_FOLDER=/logs/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  agent:
    image: "monitor-agent"
    environment:
      - HOST=server
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]