name: Agent Docker

on:
  push:
    branches: ['release', 'main']

env:
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: 'docker-swarm-monitor-agent'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
        uses: docker/setup-buildx-action@v2.5.0
#         with:
#           # Buildx version. (eg. v0.3.0)
#           version: # optional
#           # Sets the builder driver to be used
#           driver: # optional, default is docker-container
#           # List of additional driver-specific options. (eg. image=moby/buildkit:master)
#           driver-opts: # optional
#           # Flags for buildkitd daemon
#           buildkitd-flags: # optional, default is --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
#           # Sets up docker build command as an alias to docker buildx build
#           install: # optional, default is false
#           # Switch to this builder instance
#           use: # optional, default is true
#           # Optional address for docker socket or context from `docker context ls`
#           endpoint: # optional
#           # Fixed platforms for current node. If not empty, values take priority over the detected ones
#           platforms: # optional
#           # BuildKit config file
#           config: # optional
#           # Inline BuildKit config
#           config-inline: # optional
#           # Append additional nodes to the builder
#           append: # optional
#           # Cleanup temp files and remove builder at the end of a job
#           cleanup: # optional, default is true

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
